### ISSUE TITLE
Fallback - Add original image and height attribute

### ISSUE THREAD

**Issue by linkrb** [umanit/twig-image-extension#7]
To avoid the [Cumulative Layout Shift](https://web.dev/optimize-cls/?utm_source=lighthouse&utm_medium=wpt#modern-best-practice) we should add the image and height attribute. 

When we use the `thumbnail` it's ok. We take the height define in the filter 

```yaml
            filters:
                # use and setup the "thumbnail" filter
                thumbnail:
                    # set the thumbnail size to "32x32" pixels
                    size: [32, 32]
```

But with the relative filter we can't determinate the height of the image. 

```yaml
        big_filter:
            filters:
                relative_resize:
                    widen: 735
```                    
                    
If we have only **one** dimension. We need to push the height and width of the original image
With that the browser manages to [determine](https://github.com/WICG/intrinsicsize-attribute/issues/16) the ratio of the image. 

An idea -> with the `data_root` and the `path` of the image we can retrieve the width and height. 

`getimagesize($this->data_root.$path)[3];`
